language: node_js
node_js:
- stable
script: yarn run build
deploy:
  edge: true
  cleanup: false
  provider: npm
  email: nat@natwelch.com
  api_key:
    secure: cgaS/3uxzW996odLFw6yvGGGMr3GPjw5+fNuH1+JIexBQkl1cE9NKeDJaFYkBs3Fbz7CPusOTzW2nz0g3f5kfWeZN4NufMUMjzWxRAu05h4O6728FbZQnF5tseS80eRIPuVJZxgjaA3yh0CsvOfEAH7T/JrLKPEUjyIihghmoNCMrvn4qB5ALIzdV/I5xlfzCQXv9Lkn1J7nn8ZFWs8lFW23TeAT7l1b8RXxfWZF67xC6WgavzUFdNZzzz4Wsg7XsORsPPO1uGHjtJlYsike4PWJBa/dSSEqv1UrN+ur3dDx0W3ovg5xn/mx4VOfs20hTF/g2pXxkd20EUyn6RXpoRQlDKdfQ/vjixnhJAAb8PLOv4Nu7cw8Hbht/bfzfgCIE3AdB9Uj3V8cQgxsv0vtuJK+yhd3hSd7BPXXhpqf2JWxGJusnO40fPSFQZPSuWF1CnH6q8fdVmJCjn0+eNJfEGcncWqJQ318L9p3HGE19du9sCbjYHUxROm5S9byuYdDBpZkp3oF/Ja6bgh5qpITPBqOoNCcz9AGjUFtQ+lGzJihVt/OmuUnEAXN372gcjxOJCPKDZiuCKze5YKDBxLQe1zaAMZjX0YN0FOWVdxDOAbCeo9eVsZzri/uRTA9ARQ+CS3ZrC5bmiKtMz+IpVOyc4rj/Qu61qekUH8lUtjfBgk=
  on:
    tags: true
    repo: icco/pino-stackdriver-serializers
