language: node_js
node_js:
- stable
script: yarn run build
deploy:
  edge: true
  cleanup: false
  provider: npm
  email: nat@natwelch.com
  on:
    tags: true
    repo: icco/pino-stackdriver-serializers
  api_token:
    secure: sONRT1Hj0PXiNN3Ft2yNx2Sb6wwPnUlYXvZwDYY3f7HZjcG3w5JAZu/WDO5LW6H00dTfLrlI9Sxg0s+BLKivOtG/Tci1XyWR7tRAqFB+FzhUqMbR24xHlL0FQwm207guKfC6246Je45ez7bGZU/aXVjerCt01qmfgi7H+n4+M566FxuXScIEUjw8VPN8gU3M1LrXaxA3BlRK113x7+oR3SQa5cn/QYvOz3TrlEqOTsriJnoPTizPnhXsryh+0IBWTz5j8239kH2RE6ri+ZTTYF0yW+bkGJArUptqJkiQ2rrMQ5ugQGRdV4WnLX2R2Ho6BHnl/f1y75Bhy4nqw1iLbWMmY2BwtDpBJzL2ZWfhbabuhyahxUWMa6v1IR7xhSiFkB+tr8DPSBuT0vfuBQZiL/++OCdy+UCBTWwiG550XNj7i/K5AeK5Od9SVFJTUJykzuSgZWwXL3jHfaaEokrGX/8IDAOO6mKxv7f6H1VEzDNBOT1O2SxDfTRk9ne20tpgkE+HYfF00Fz4iN451eQgiAshRuFezh1/8Zt1o1enc6wNpMpw9PJNVtEmKVfMUOV9NLB1/HZa4lZ6+DjbM8hL7htom3eJXOmuatVOChqyOQ/6cZ7WK4NHmch3DNwqkZF1Iqbt7QIPPusIKuQRZnC+zl3sH3TM/tI2jFa3d0WvUdA=
